services:
  - type: web
    name: learnhub-backend
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false          # You must set this manually in Render dashboard
      - key: JDOODLE_CLIENT_ID
        sync: false          # You must set this manually in Render dashboard
      - key: JDOODLE_CLIENT_SECRET
        sync: false          # You must set this manually in Render dashboard
      - key: FRONTEND_URL
        value: https://learnhub-project-eight.vercel.app
